apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Optional: create a namespace for all resources
namespace: employees-app

# List all the YAML files to apply
resources:
  - namespace.yaml
  #- zookeeper-deployment.yaml
  # - kafka-deployment.yaml
  - dynamodb-deployment.yaml
  - employee-deployment.yaml
