name: CI/CD for Employee Service

on:
  #push:
    #branches:
      #- main
  workflow_dispatch:
  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      KUBECONFIG: kubeconfig 

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/dummy-projects:employee-service ./employees

      # 4. Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/dummy-projects:employee-service


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Install aws-iam-authenticator
        run: |
          curl -o aws-iam-authenticator \
            https://amazon-eks.s3.us-west-2.amazonaws.com/1.27.3/2023-07-05/bin/linux/amd64/aws-iam-authenticator
          chmod +x aws-iam-authenticator
          sudo mv aws-iam-authenticator /usr/local/bin/


      # 5. Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.32.0'


      # 6. Configure kubeconfig
      - name: Configure kubeconfig
        run: |
          echo "${{ env.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig
          export KUBECONFIG=kubeconfig

      # 7. Test connection
      - name: Test Connection
        run: |
          kubectl get nodes

      # 8. Apply Kubernetes manifests
      - name: Deploy to EKS
        run: |
          kubectl apply -f employees/k8s/
