name: CI/CD for Employee Service

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::154534185443:role/Github_EKS_Deploy_Role
          aws-region: ap-southeast-2

      - name: Setup AWS EKS
        uses: aws-actions/setup-aws-eks@v1
        with:
          cluster-name: employee-cluster

      - name: Deploy application
        run: |
          kubectl apply -f employees/k8s/dynamodb-deployment.yaml
          kubectl apply -f employees/k8s/employee-deployment.yaml
