name: CI/CD for Employee Service

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::154534185443:role/Github_EKS_Deploy_Role
          aws-region: ap-southeast-2

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.27.0'  # or 'latest'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name employee-cluster --region ap-southeast-2

      - name: Deploy application
        run: |
          kubectl apply -f employees/k8s/dynamodb-deployment.yaml
          kubectl apply -f employees/k8s/employee-deployment.yaml
